### ISSUE TITLE
Can you add a "Display Code/Furigana" Option for Furigana?

### ISSUE THREAD

**Issue by Nukemarine** [jcsirot/anki-simple-furigana#3]
The previous program you based off this could do that. It shows the text as the code would be outside of anki: ex: japanese[furigana]; japanese2[furigana2]; japanese3[furigana3], etc. While I can edit the card right now (little tedious and easy to mess up), this would make it easier as the text for the furigana would be the same font size along with easy bracket placement

**Comment by jcsirot** [comment]
I added an option to use square brackets instead of ruby html tags. This option is available in version 1.0.0 just released on AnkiWeb. I hope this helps.
