### ISSUE TITLE
Some characters not generating furigana.

### ISSUE THREAD

**Issue by RoseyMarie** [jcsirot/anki-simple-furigana#5]
I tried generating furigana for a whole field (everything but ニ generated) and for just ニ  by selecting just that kanji and neither resulted in furigana generation.

**Comment by RoseyMarie** [comment]
六 also doesn't generate furigana

**Comment by RoseyMarie** [comment]
三 either so it must be a thing with number related Kanji

**Comment by RoseyMarie** [comment]
一 works but 十 doesn't

**Comment by jcsirot** [comment]
I wanted to mimic the ClozeFuriganaTools add-on behavior which did not add furiganas for the kanjis representing numbers (from 1 to 10). Maybe I could add an option to make it possible.

**Comment by jcsirot** [comment]
I added an option in the 1.0.0 version. It is possible to add furigana on "number" kanjis. Unfortunately MeCab, the syntax analyser does not handle irregular readings very well (like ふたり for 二人 or いっぽん for 一本) therefore from time to time it is required to fix the incorrect generated readings.
